# Generated by Django 5.2.5 on 2025-09-17 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrationg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRationg',
            new_name='ReviewRating',
        ),
    ]
