# Generated by Django 5.2.5 on 2025-09-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Variation',
            new_name='variation',
        ),
    ]
