# Generated by Django 5.2.5 on 2025-09-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_payment_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.CharField(max_length=200),
        ),
    ]
